BASE_URL=https://api.escuelajs.co/api/v1
STORED_SCHEMA_PATH = /schemas
GAMMAZON_BACKEND_URI= http://localhost:8001
KAFKA_CONSUMER_URI= http://localhost:8000
KAFKA_PRODUCER_URI= http://localhost:8080
MONGODB_URI=mongodb://localhost:27017
MONGODB_DATABASE=ecommerce_db
PRODUCER_IMAGE=kafka_event_streaming_system-producer-app:latest
CONSUMER_IMAGE=kafka_event_streaming_system-consumer-app:latest